name: Test deploy for tf and ansible
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan
      
    # - name: Terraform Apply
    #   working-directory: terraform
    #   run: terraform apply -auto-approve

    - name: Terraform Destroy
      working-directory: terraform
      run: terraform destroy -auto-approve


    # - name: Export Terraform outputs to environment variables
    #   id: outputs
    #   run: |
    #     echo "BASTION_IP=$(terraform output -raw bastion_public_ip)" >> $GITHUB_ENV
    #     echo "RESOURCE_SERVER_IP=$(terraform output -raw resource_server_private_ip)" >> $GITHUB_ENV

  # ansible:
  #   runs-on: ubuntu-latest
  #   needs: terraform

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Install Ansible
  #     run: sudo apt-get update && sudo apt-get install -y ansible

  #   - name: Setup SSH keys for Bastion Host
  #     run: |
  #       mkdir -p ~/.ssh
  #       echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
  #       chmod 600 ~/.ssh/id_rsa
  #     env:
  #       PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY }}

  #   - name: Install Ansible dependencies
  #     run: |
  #       ansible-galaxy install -r requirements.yml  # If you have additional roles
  #       ansible-playbook -i inventory.ini bastion.yml
  #       ansible-playbook -i inventory.ini resource_server.yml
